export interface MemeTemplate {
  id: string
  name: string
  file: string
  width: number
  height: number
  boxCount: number
  tags: string[]
}

export const MEME_TEMPLATES: MemeTemplate[] = [
  {
    id: "181913649",
    name: "Drake Hotline Bling",
    file: "/memes/181913649.jpg",
    width: 1200,
    height: 1200,
    boxCount: 2,
    tags: ["comparison", "preference", "choosing", "old vs new", "better", "worse", "rejection", "approval"],
  },
  {
    id: "87743020",
    name: "Two Buttons",
    file: "/memes/87743020.jpg",
    width: 600,
    height: 908,
    boxCount: 3,
    tags: ["choice", "dilemma", "decision", "trade-off", "options", "stress", "conflict", "indecision"],
  },
  {
    id: "112126428",
    name: "Distracted Boyfriend",
    file: "/memes/112126428.jpg",
    width: 1200,
    height: 800,
    boxCount: 3,
    tags: ["distraction", "temptation", "switching", "attention", "new thing", "betrayal", "preference", "jealousy"],
  },
  {
    id: "217743513",
    name: "UNO Draw 25 Cards",
    file: "/memes/217743513.jpg",
    width: 500,
    height: 600,
    boxCount: 2,
    tags: ["avoidance", "refusal", "alternative", "consequences", "stubborn", "denial", "choice"],
  },
  {
    id: "222403160",
    name: "Bernie I Am Once Again Asking For Your Support",
    file: "/memes/222403160.jpg",
    width: 960,
    height: 540,
    boxCount: 2,
    tags: ["asking", "pleading", "request", "repeat", "persistence", "donation", "support", "politics"],
  },
  {
    id: "124822590",
    name: "Left Exit 12 Off Ramp",
    file: "/memes/124822590.jpg",
    width: 804,
    height: 767,
    boxCount: 3,
    tags: ["choice", "detour", "preference", "switching", "distraction", "comparison", "better option"],
  },
  {
    id: "252600902",
    name: "Always Has Been",
    file: "/memes/252600902.jpg",
    width: 1187,
    height: 671,
    boxCount: 2,
    tags: ["revelation", "always true", "surprise", "realization", "conspiracy", "discovery", "secret"],
  },
  {
    id: "322841258",
    name: "Anakin Padme 4 Panel",
    file: "/memes/322841258.jpg",
    width: 1200,
    height: 1200,
    boxCount: 3,
    tags: ["expectation", "hope", "confirmation", "dark truth", "comedy", "assumption", "implication"],
  },
  {
    id: "131087935",
    name: "Running Away Balloon",
    file: "/memes/131087935.jpg",
    width: 761,
    height: 1024,
    boxCount: 5,
    tags: ["escape", "running", "avoidance", "letting go", "freedom", "rejection", "distraction"],
  },
  {
    id: "131940431",
    name: "Gru's Plan",
    file: "/memes/131940431.jpg",
    width: 1264,
    height: 1460,
    boxCount: 4,
    tags: ["plan", "backfire", "strategy", "unexpected", "steps", "mistake", "fail", "comedy"],
  },
  {
    id: "135256802",
    name: "Epic Handshake",
    file: "/memes/135256802.jpg",
    width: 900,
    height: 900,
    boxCount: 3,
    tags: ["agreement", "unity", "common ground", "both", "cooperation", "shared", "equal", "alliance"],
  },
  {
    id: "80707627",
    name: "Sad Pablo Escobar",
    file: "/memes/80707627.jpg",
    width: 1200,
    height: 900,
    boxCount: 3,
    tags: ["boredom", "waiting", "loneliness", "sadness", "nothing to do", "empty", "isolation"],
  },
  {
    id: "97984",
    name: "Disaster Girl",
    file: "/memes/97984.jpg",
    width: 500,
    height: 375,
    boxCount: 2,
    tags: ["chaos", "disaster", "evil", "smug", "destruction", "fire", "satisfaction", "dark"],
  },
  {
    id: "91538330",
    name: "X, X Everywhere",
    file: "/memes/91538330.jpg",
    width: 580,
    height: 434,
    boxCount: 2,
    tags: ["everywhere", "abundance", "overload", "too much", "spam", "presence", "ubiquitous"],
  },
  {
    id: "4087833",
    name: "Waiting Skeleton",
    file: "/memes/4087833.jpg",
    width: 500,
    height: 500,
    boxCount: 2,
    tags: ["waiting", "patience", "long time", "forever", "slow", "delay", "anticipation"],
  },
  {
    id: "102156234",
    name: "Mocking Spongebob",
    file: "/memes/102156234.jpg",
    width: 502,
    height: 353,
    boxCount: 2,
    tags: ["mockery", "sarcasm", "mimicking", "ridicule", "alternating", "silly", "taunt"],
  },
  {
    id: "438680",
    name: "Batman Slapping Robin",
    file: "/memes/438680.jpg",
    width: 400,
    height: 300,
    boxCount: 2,
    tags: ["interruption", "correction", "stop", "disagreement", "slap", "shut up", "rejection"],
  },
  {
    id: "129242436",
    name: "Change My Mind",
    file: "/memes/129242436.jpg",
    width: 482,
    height: 361,
    boxCount: 2,
    tags: ["debate", "argument", "challenge", "opinion", "hypothesis", "bold claim", "confident", "controversial"],
  },
  {
    id: "188390779",
    name: "Woman Yelling At Cat",
    file: "/memes/188390779.jpg",
    width: 680,
    height: 352,
    boxCount: 2,
    tags: ["argument", "disagreement", "conflict", "misunderstanding", "calm vs angry", "accusation", "reaction"],
  },
  {
    id: "309868304",
    name: "Trade Offer",
    file: "/memes/309868304.jpg",
    width: 1080,
    height: 1080,
    boxCount: 3,
    tags: ["trade", "deal", "negotiation", "exchange", "offer", "bargain", "transaction"],
  },
  {
    id: "124055727",
    name: "Y'all Got Any More Of That",
    file: "/memes/124055727.jpg",
    width: 590,
    height: 421,
    boxCount: 2,
    tags: ["craving", "addiction", "wanting more", "desperation", "hunger", "need", "demand"],
  },
  {
    id: "247375501",
    name: "Buff Doge vs. Cheems",
    file: "/memes/247375501.jpg",
    width: 937,
    height: 720,
    boxCount: 4,
    tags: ["comparison", "strong vs weak", "then vs now", "past vs present", "power", "contrast", "expectation vs reality"],
  },
  {
    id: "93895088",
    name: "Expanding Brain",
    file: "/memes/93895088.jpg",
    width: 857,
    height: 1202,
    boxCount: 4,
    tags: ["complexity", "levels", "escalation", "advanced", "thinking", "evolution", "galaxy brain", "progression"],
  },
  {
    id: "55311130",
    name: "This Is Fine",
    file: "/memes/55311130.jpg",
    width: 580,
    height: 282,
    boxCount: 2,
    tags: ["problems", "denial", "overwhelm", "crisis", "ignoring", "calm", "fire", "everything is fine"],
  },
  {
    id: "178591752",
    name: "Tuxedo Winnie The Pooh",
    file: "/memes/178591752.jpg",
    width: 1200,
    height: 1199,
    boxCount: 2,
    tags: ["fancy", "elegant", "comparison", "upgrade", "better version", "sophisticated", "classy", "same but different"],
  },
  {
    id: "61579",
    name: "One Does Not Simply",
    file: "/memes/61579.jpg",
    width: 568,
    height: 335,
    boxCount: 2,
    tags: ["difficulty", "impossible", "challenge", "warning", "serious", "caution", "not easy"],
  },
  {
    id: "79132341",
    name: "Bike Fall",
    file: "/memes/79132341.jpg",
    width: 500,
    height: 680,
    boxCount: 3,
    tags: ["self-sabotage", "own fault", "mistake", "causing problems", "irony", "blame", "accident"],
  },
  {
    id: "100777631",
    name: "Is This A Pigeon",
    file: "/memes/100777631.jpg",
    width: 640,
    height: 360,
    boxCount: 3,
    tags: ["misidentification", "confusion", "wrong", "label", "misunderstanding", "naive", "incorrect assumption"],
  },
  {
    id: "101470",
    name: "Ancient Aliens",
    file: "/memes/101470.jpg",
    width: 500,
    height: 437,
    boxCount: 2,
    tags: ["conspiracy", "aliens", "explanation", "crazy theory", "mysterious", "supernatural", "alternative explanation"],
  },
  {
    id: "252758727",
    name: "Mother Ignoring Kid Drowning In A Pool",
    file: "/memes/252758727.jpg",
    width: 568,
    height: 379,
    boxCount: 4,
    tags: ["ignoring", "distraction", "priorities", "neglect", "phone", "attention", "irresponsible"],
  },
  {
    id: "505705955",
    name: "Absolute Cinema",
    file: "/memes/505705955.jpg",
    width: 1078,
    height: 657,
    boxCount: 2,
    tags: ["masterpiece", "amazing", "cinematic", "art", "impressive", "brilliant", "quality", "epic"],
  },
  {
    id: "427308417",
    name: "0 days without (Lenny, Simpsons)",
    file: "/memes/427308417.jpg",
    width: 800,
    height: 450,
    boxCount: 2,
    tags: ["failure", "accident", "recurring", "again", "incident", "counter", "zero days", "reset"],
  },
  {
    id: "161865971",
    name: "Marked Safe From",
    file: "/memes/161865971.jpg",
    width: 960,
    height: 960,
    boxCount: 2,
    tags: ["safe", "survival", "avoided", "escaped", "relief", "protected", "immune"],
  },
  {
    id: "180190441",
    name: "They're The Same Picture",
    file: "/memes/180190441.jpg",
    width: 1200,
    height: 676,
    boxCount: 3,
    tags: ["same", "identical", "comparison", "similarity", "equivalent", "no difference", "equal"],
  },
  {
    id: "224015000",
    name: "Bernie Sanders Once Again Asking",
    file: "/memes/224015000.jpg",
    width: 1066,
    height: 600,
    boxCount: 2,
    tags: ["asking", "pleading", "request", "repeat", "cold", "persistence", "mittens", "politics"],
  },
  {
    id: "195515965",
    name: "Clown Applying Makeup",
    file: "/memes/195515965.jpg",
    width: 444,
    height: 618,
    boxCount: 4,
    tags: ["fool", "clown", "self-deception", "fooling yourself", "irony", "silly belief", "delusion"],
  },
  {
    id: "110163934",
    name: "I Bet He's Thinking About Other Women",
    file: "/memes/110163934.jpg",
    width: 960,
    height: 640,
    boxCount: 2,
    tags: ["thinking", "distraction", "imagination", "daydream", "curiosity", "suspicion", "deep thought"],
  },
  {
    id: "177682295",
    name: "You Guys are Getting Paid",
    file: "/memes/177682295.jpg",
    width: 600,
    height: 362,
    boxCount: 2,
    tags: ["unpaid", "volunteer", "compensation", "fair pay", "expectation", "surprise", "labor"],
  },
  {
    id: "370867422",
    name: "Megamind peeking",
    file: "/memes/370867422.jpg",
    width: 1280,
    height: 720,
    boxCount: 2,
    tags: ["sneaky", "watching", "curious", "peeking", "spying", "interest", "observing"],
  },
  {
    id: "3218037",
    name: "This Is Where I'd Put My Trophy If I Had One",
    file: "/memes/3218037.jpg",
    width: 500,
    height: 375,
    boxCount: 2,
    tags: ["empty", "missing", "lack", "absence", "wish", "hypothetical", "if only"],
  },
  {
    id: "148909805",
    name: "Monkey Puppet",
    file: "/memes/148909805.jpg",
    width: 473,
    height: 498,
    boxCount: 2,
    tags: ["awkward", "side eye", "uncomfortable", "nervous", "caught", "embarrassed", "suspicious"],
  },
  {
    id: "28251713",
    name: "Oprah You Get A",
    file: "/memes/28251713.jpg",
    width: 500,
    height: 278,
    boxCount: 2,
    tags: ["giving", "generosity", "everyone gets", "distribution", "abundance", "free", "giveaway"],
  },
  {
    id: "67452763",
    name: "Squidward window",
    file: "/memes/67452763.jpg",
    width: 600,
    height: 450,
    boxCount: 2,
    tags: ["jealousy", "watching", "envy", "peering", "longing", "observing", "desire"],
  },
  {
    id: "61544",
    name: "Success Kid",
    file: "/memes/61544.jpg",
    width: 500,
    height: 500,
    boxCount: 2,
    tags: ["success", "win", "achievement", "victory", "celebration", "happy", "fist pump"],
  },
  {
    id: "247756783",
    name: "patrick to do list actually blank",
    file: "/memes/247756783.jpg",
    width: 940,
    height: 697,
    boxCount: 3,
    tags: ["empty", "blank", "nothing", "lazy", "no plan", "zero tasks", "nothing to do"],
  },
  {
    id: "1035805",
    name: "Boardroom Meeting Suggestion",
    file: "/memes/1035805.jpg",
    width: 600,
    height: 400,
    boxCount: 4,
    tags: ["suggestion", "rejection", "meeting", "corporate", "workplace", "ignored", "proposal"],
  },
  {
    id: "77045868",
    name: "Pawn Stars Best I Can Do",
    file: "/memes/77045868.jpg",
    width: 600,
    height: 338,
    boxCount: 2,
    tags: ["negotiation", "low offer", "compromise", "best deal", "trade", "bargain", "value"],
  },
  {
    id: "27813981",
    name: "Hide the Pain Harold",
    file: "/memes/27813981.jpg",
    width: 400,
    height: 400,
    boxCount: 2,
    tags: ["pain", "hiding feelings", "smile through pain", "pretending", "fake happiness", "suffering", "mask"],
  },
  {
    id: "119139145",
    name: "Blank Nut Button",
    file: "/memes/119139145.jpg",
    width: 600,
    height: 401,
    boxCount: 2,
    tags: ["trigger", "button", "reaction", "excitement", "compulsion", "instinct", "temptation"],
  },
  {
    id: "259237855",
    name: "Laughing Leo",
    file: "/memes/259237855.jpg",
    width: 785,
    height: 441,
    boxCount: 2,
    tags: ["laughing", "amused", "pointing", "ridicule", "funny", "humor", "irony"],
  },
  {
    id: "84341851",
    name: "Evil Kermit",
    file: "/memes/84341851.jpg",
    width: 536,
    height: 354,
    boxCount: 2,
    tags: ["temptation", "evil side", "inner voice", "dark thoughts", "devil", "conscience", "impulse"],
  },
  {
    id: "533936279",
    name: "Bell Curve",
    file: "/memes/533936279.jpg",
    width: 1200,
    height: 840,
    boxCount: 3,
    tags: ["statistics", "distribution", "extreme", "middle", "average", "normal", "smart vs dumb", "galaxy brain"],
  },
  {
    id: "171305372",
    name: "Soldier protecting sleeping child",
    file: "/memes/171305372.jpg",
    width: 600,
    height: 400,
    boxCount: 3,
    tags: ["protection", "guarding", "safe", "security", "precious", "shield", "defending"],
  },
  {
    id: "226297822",
    name: "Panik Kalm Panik",
    file: "/memes/226297822.jpg",
    width: 444,
    height: 618,
    boxCount: 3,
    tags: ["panic", "calm", "anxiety", "relief", "worry", "stress", "rollercoaster", "reaction"],
  },
  {
    id: "284929871",
    name: "They don't know",
    file: "/memes/284929871.jpg",
    width: 700,
    height: 700,
    boxCount: 2,
    tags: ["secret", "alone", "party", "knowing", "hidden knowledge", "awareness", "isolated"],
  },
  {
    id: "89370399",
    name: "Roll Safe Think About It",
    file: "/memes/89370399.jpg",
    width: 702,
    height: 395,
    boxCount: 2,
    tags: ["loophole", "clever", "smart", "galaxy brain", "logic", "trick", "hack", "avoid problem"],
  },
  {
    id: "166969924",
    name: "Flex Tape",
    file: "/memes/166969924.jpg",
    width: 482,
    height: 311,
    boxCount: 3,
    tags: ["fix", "solution", "duct tape", "quick fix", "problem solving", "patching", "repair"],
  },
  {
    id: "61520",
    name: "Futurama Fry",
    file: "/memes/61520.jpg",
    width: 569,
    height: 379,
    boxCount: 2,
    tags: ["unsure", "not sure if", "suspicion", "doubt", "skeptical", "squinting", "uncertainty"],
  },
  {
    id: "99683372",
    name: "Sleeping Shaq",
    file: "/memes/99683372.jpg",
    width: 538,
    height: 566,
    boxCount: 2,
    tags: ["unaffected", "sleeping", "ignoring", "unbothered", "don't care", "relaxed", "indifferent"],
  },
  {
    id: "316466202",
    name: "where monkey",
    file: "/memes/316466202.jpg",
    width: 1200,
    height: 900,
    boxCount: 2,
    tags: ["missing", "where", "lost", "searching", "confused", "gone", "looking for"],
  },
  {
    id: "114585149",
    name: "Inhaling Seagull",
    file: "/memes/114585149.jpg",
    width: 1066,
    height: 600,
    boxCount: 4,
    tags: ["mine", "possessive", "greedy", "wanting", "claiming", "desire", "taking"],
  },
  {
    id: "206151308",
    name: "Spider Man Triple",
    file: "/memes/206151308.jpg",
    width: 500,
    height: 361,
    boxCount: 3,
    tags: ["same", "identical", "pointing", "accusation", "duplicate", "copy", "similar"],
  },
  {
    id: "155067746",
    name: "Surprised Pikachu",
    file: "/memes/155067746.jpg",
    width: 1893,
    height: 1893,
    boxCount: 3,
    tags: ["surprise", "unexpected", "obvious", "consequence", "reaction", "shocked", "foreseeable"],
  },
  {
    id: "135678846",
    name: "Who Killed Hannibal",
    file: "/memes/135678846.jpg",
    width: 500,
    height: 500,
    boxCount: 3,
    tags: ["betrayal", "blame", "confusion", "self-inflicted", "irony", "accusation", "own fault"],
  },
  {
    id: "234202281",
    name: "AJ Styles & Undertaker",
    file: "/memes/234202281.jpg",
    width: 750,
    height: 438,
    boxCount: 2,
    tags: ["respect", "admiration", "bowing", "honor", "appreciation", "salute", "worship"],
  },
  {
    id: "137501417",
    name: "Friendship ended",
    file: "/memes/137501417.jpg",
    width: 500,
    height: 501,
    boxCount: 2,
    tags: ["ended", "replaced", "new best friend", "switching", "loyalty", "change", "upgrade"],
  },
  {
    id: "208915813",
    name: "George Bush 9/11",
    file: "/memes/208915813.jpg",
    width: 828,
    height: 1024,
    boxCount: 2,
    tags: ["disaster", "reading", "oblivious", "news", "unaware", "ignorance", "moment"],
  },
  {
    id: "101956210",
    name: "Whisper and Goosebumps",
    file: "/memes/101956210.jpg",
    width: 700,
    height: 467,
    boxCount: 2,
    tags: ["fear", "goosebumps", "scary", "creepy", "dread", "horror", "chilling"],
  },
  {
    id: "119215120",
    name: "Types of Headaches meme",
    file: "/memes/119215120.jpg",
    width: 500,
    height: 522,
    boxCount: 2,
    tags: ["headache", "pain", "stress", "categories", "types", "labeled", "problems"],
  },
  {
    id: "354700819",
    name: "Two guys on a bus",
    file: "/memes/354700819.jpg",
    width: 1200,
    height: 576,
    boxCount: 2,
    tags: ["different reactions", "one scared one calm", "contrast", "fear vs calm", "perspective", "response"],
  },
  {
    id: "187102311",
    name: "Three-headed Dragon",
    file: "/memes/187102311.jpg",
    width: 2048,
    height: 1116,
    boxCount: 4,
    tags: ["three things", "combination", "unite", "all together", "agreement", "triple", "alliance"],
  },
  {
    id: "247113703",
    name: "A train hitting a school bus",
    file: "/memes/247113703.jpg",
    width: 680,
    height: 374,
    boxCount: 2,
    tags: ["collision", "crash", "inevitable", "disaster", "unstoppable", "impact", "incoming"],
  },
  {
    id: "224514655",
    name: "Anime Girl Hiding from Terminator",
    file: "/memes/224514655.jpg",
    width: 900,
    height: 900,
    boxCount: 2,
    tags: ["hiding", "fear", "avoidance", "threat", "escape", "protection", "danger"],
  },
  {
    id: "110133729",
    name: "spiderman pointing at spiderman",
    file: "/memes/110133729.jpg",
    width: 765,
    height: 430,
    boxCount: 2,
    tags: ["same", "identical", "pointing", "duplicate", "mirror", "accusation", "both"],
  },
  {
    id: "221578498",
    name: "Grant Gustin over grave",
    file: "/memes/221578498.jpg",
    width: 602,
    height: 800,
    boxCount: 2,
    tags: ["mourning", "death", "end", "replaced", "old vs new", "grief", "successor"],
  },
  {
    id: "91545132",
    name: "Trump Bill Signing",
    file: "/memes/91545132.jpg",
    width: 500,
    height: 375,
    boxCount: 2,
    tags: ["signing", "official", "decree", "announcement", "approval", "law", "policy"],
  },
  {
    id: "61556",
    name: "Grandma Finds The Internet",
    file: "/memes/61556.jpg",
    width: 500,
    height: 500,
    boxCount: 2,
    tags: ["internet", "technology", "confused", "discovery", "generations", "new tech", "learning"],
  },
  {
    id: "5496396",
    name: "Leonardo Dicaprio Cheers",
    file: "/memes/5496396.jpg",
    width: 508,
    height: 472,
    boxCount: 2,
    tags: ["cheers", "toast", "celebration", "recognition", "pointing", "spotted", "that's it"],
  },
  {
    id: "309668311",
    name: "Two Paths",
    file: "/memes/309668311.jpg",
    width: 1200,
    height: 780,
    boxCount: 3,
    tags: ["choice", "path", "decision", "fork", "direction", "options", "crossroads"],
  },
  {
    id: "101288",
    name: "Third World Skeptical Kid",
    file: "/memes/101288.jpg",
    width: 405,
    height: 428,
    boxCount: 2,
    tags: ["skeptical", "doubt", "disbelief", "really?", "questioning", "side-eye", "unconvinced"],
  },
  {
    id: "145139900",
    name: "Scooby doo mask reveal",
    file: "/memes/145139900.jpg",
    width: 1200,
    height: 627,
    boxCount: 4,
    tags: ["reveal", "unmasking", "true identity", "disguise", "exposed", "plot twist", "behind the scenes"],
  },
  {
    id: "162372564",
    name: "Domino Effect",
    file: "/memes/162372564.jpg",
    width: 720,
    height: 690,
    boxCount: 2,
    tags: ["chain reaction", "domino", "cascade", "sequence", "cause and effect", "progression", "knock-on"],
  },
  {
    id: "129315248",
    name: "No - Yes",
    file: "/memes/129315248.jpg",
    width: 1200,
    height: 1200,
    boxCount: 2,
    tags: ["yes", "no", "choice", "approval", "denial", "decision", "opposite"],
  },
  {
    id: "134797956",
    name: "American Chopper Argument",
    file: "/memes/134797956.jpg",
    width: 600,
    height: 757,
    boxCount: 5,
    tags: ["argument", "debate", "back and forth", "conflict", "escalation", "disagreement", "heated"],
  },
  {
    id: "14371066",
    name: "Star Wars Yoda",
    file: "/memes/14371066.jpg",
    width: 600,
    height: 468,
    boxCount: 2,
    tags: ["wisdom", "advice", "yoda", "guidance", "philosophy", "star wars", "teaching"],
  },
  {
    id: "29617627",
    name: "Look At Me",
    file: "/memes/29617627.jpg",
    width: 500,
    height: 353,
    boxCount: 2,
    tags: ["authority", "control", "power", "takeover", "now in charge", "leadership", "transition"],
  },
  {
    id: "371619279",
    name: "Megamind no bitches",
    file: "/memes/371619279.jpg",
    width: 1198,
    height: 674,
    boxCount: 2,
    tags: ["zero", "none", "nobody", "empty", "failure", "lack", "nothing"],
  },
  {
    id: "216523697",
    name: "All My Homies Hate",
    file: "/memes/216523697.jpg",
    width: 1199,
    height: 859,
    boxCount: 2,
    tags: ["hate", "against", "group opinion", "rejection", "dislike", "consensus", "opposition"],
  },
  {
    id: "123999232",
    name: "The Scroll Of Truth",
    file: "/memes/123999232.jpg",
    width: 640,
    height: 449,
    boxCount: 2,
    tags: ["truth", "revelation", "wisdom", "deny", "uncomfortable truth", "reality", "fact"],
  },
  {
    id: "360597639",
    name: "whe i'm in a competition and my opponent is",
    file: "/memes/360597639.jpg",
    width: 693,
    height: 889,
    boxCount: 2,
    tags: ["competition", "opponent", "intimidating", "challenge", "rival", "fear", "match"],
  },
  {
    id: "50421420",
    name: "Disappointed Black Guy",
    file: "/memes/50421420.jpg",
    width: 600,
    height: 360,
    boxCount: 2,
    tags: ["disappointment", "sad", "let down", "unimpressed", "expectation vs reality", "underwhelmed"],
  },
  {
    id: "92084495",
    name: "Charlie Conspiracy (Always Sunny in Philidelphia)",
    file: "/memes/92084495.jpg",
    width: 800,
    height: 450,
    boxCount: 2,
    tags: ["conspiracy", "theory", "connected", "crazy", "overthinking", "investigation", "pattern"],
  },
  {
    id: "21735",
    name: "The Rock Driving",
    file: "/memes/21735.jpg",
    width: 720,
    height: 540,
    boxCount: 2,
    tags: ["wait what", "double take", "surprise", "realization", "sudden awareness", "look again"],
  },
  {
    id: "29562797",
    name: "I'm The Captain Now",
    file: "/memes/29562797.jpg",
    width: 600,
    height: 380,
    boxCount: 2,
    tags: ["takeover", "in charge", "power", "new boss", "authority", "replaced", "leadership"],
  },
  {
    id: "72525473",
    name: "say the line bart! simpsons",
    file: "/memes/72525473.jpg",
    width: 728,
    height: 546,
    boxCount: 3,
    tags: ["expected", "predictable", "say it", "crowd pleasing", "repetition", "popular saying", "catchphrase"],
  },
  {
    id: "142009471",
    name: "is this butterfly",
    file: "/memes/142009471.jpg",
    width: 500,
    height: 375,
    boxCount: 3,
    tags: ["misidentification", "confusion", "wrong", "label", "misunderstanding", "naive", "is this"],
  },
  {
    id: "6235864",
    name: "Finding Neverland",
    file: "/memes/6235864.jpg",
    width: 500,
    height: 316,
    boxCount: 3,
    tags: ["beautiful", "imagination", "wonder", "creativity", "heartwarming", "emotional", "inspiring"],
  },
  {
    id: "163573",
    name: "Imagination Spongebob",
    file: "/memes/163573.jpg",
    width: 500,
    height: 400,
    boxCount: 2,
    tags: ["imagination", "rainbow", "idea", "creative", "dreaming", "possibility", "vision"],
  },
  {
    id: "196652226",
    name: "Spongebob Ight Imma Head Out",
    file: "/memes/196652226.jpg",
    width: 700,
    height: 535,
    boxCount: 2,
    tags: ["leaving", "exit", "done", "goodbye", "nope", "awkward", "escape"],
  },
  {
    id: "61532",
    name: "The Most Interesting Man In The World",
    file: "/memes/61532.jpg",
    width: 568,
    height: 335,
    boxCount: 2,
    tags: ["interesting", "rare", "sophisticated", "preference", "unique", "not always but when"],
  },
]
